# Generated by Django 5.0.2 on 2024-04-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactenquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
